### ISSUE TITLE
Editing Job Types 

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale-ui#128] opened 2019-06-14 17:36 UTC
~Should be able to change is_active status.~
Should be able to override resource requirements.  (yes that is part of a larger issue)

**Comment by ericsvendsen-mil** [comment] 2019-06-14 18:32
If a task is part of something larger, I would recommend moving that to its own issue.

**Comment by ericsvendsen-mil** [comment] 2019-06-24 12:32
Editing job types needs more development and testing. Will be sure to include `is_active` status, however I'm not sure about resource requirements.

**Comment by Rachel-ais** [comment] 2019-06-24 18:02
When pausing and resuming a Job Type I am getting a Console error "ERROR TypeError: Cannot read property 'is_paused' of null" and being redirected to a blank page. When refreshing the action is successful and does update the job type.

**Comment by ericsvendsen-mil** [comment] 2019-06-25 01:19
Configuration drop downs when editing a pre-exisiting job type
Steps to reproduce:

select an existing job type.
click edit
click on the (2) Configuration page,
try to change the drop downs for workspaces.

**Comment by ericsvendsen-mil** [comment] 2019-06-25 01:20
I am seeing more issues specifically when configuration is selected while editing. It stops you from being able to use the Navigation bar with the error: "Cannot read property 'files' of undefined".

Also when selecting configuration it doesn't turn the numbered circle blue.

**Comment by emimaesmith** [comment] 2019-06-26 02:12
When editing an existing job type the configuration screen throws an error: `Cannot find control with path: 'configuration -> output_workspaces -> outputs -> output_text`. Causes the workspace drop-downs not to be populated.

Viewing the job type via the JSON mode view has a bunch of what looks like UI service json included. Not sure if this is what's causing config issues or not.

**Comment by ericsvendsen-mil** [comment] 2019-07-03 19:40
To make JSON changes to a job-type
Open job-type
Click edit,
Click JSON button
Make changes to text
Click JSON button AGAIN to close,
Then validate. (Via hamburger menu or step 4)
Then click step 4.
Then click "Edit" button

For discussion:
Streamline the process considerably with:
Change the "JSON button AGAIN to close" to a "validate" ; and add a "revert/abandon/cancel" button.
Then change the hamburger menu AND step-4 button to include both "save" and add a "revert/abandon/cancel" changes.

That way we get a validation when they're done editing JSON. And the user has two intuitive ways to save. Hamburger menu, or move to bottom of step 4 and save.

**Comment by ericsvendsen-mil** [comment] 2019-07-09 17:24
Most of the issues in this thread should be fixed by #178. Added the "discussion needed" label for figuring out the UX issues Chris raised in the above comment.

**Comment by ericsvendsen-mil** [comment] 2019-07-10 14:31
Add switches to change boolean fields (e.g. `is_published`)

**Comment by JohnPTobe** [comment] 2019-07-10 14:38
You should be able to edit a job type's docker_image field via the POST /job-types endpoint.
https://ngageoint.github.io/scale/docs/rest/v6/job_type.html#v6-add-seed-image
Just give the manifest and docker_image arguments and it will create a revision and update the docker_image field.

**Comment by ericsvendsen-mil** [comment] 2019-07-11 14:05
Add the ability back in to pause all job types, and show a warning for system jobs

**Comment by ericsvendsen-mil** [comment] 2019-07-15 14:33
@JohnPTobe maybe we discussed this, but I can't remember. How should I decide whether to use the PATCH vs POST endpoints? Should I go by whether a field can be changed via PATCH?

**Comment by emimaesmith** [comment] 2019-07-15 19:20
It appears the discrepancies between the job-type validation and job-type creation is due to the JSON created by the UI when sending the create request. Example manifest that validates via the Seed CLI, as well as the UI, but fails with a `Seed Manifest invalid` error upon creation:

Manifest:
```
{
  "seedVersion": "1.0.0",
  "job": {
    "name": "mini-job",
    "jobVersion": "1.0.0",
    "packageVersion": "1.0.0",
    "title": "Mini Job",
    "description": "Super Mini Job",
    "tags": [
      "mini"
    ],
    "maintainer": {
      "name": "Emily Smith",
      "email": "jdoe@example.com"
    },
    "timeout": 3600,
    "interface": {
      "command": "${OUTPUT_DIR}",
      "outputs": {
        "files": [
          {
            "name": "output_file_pngs",
            "mediaType": "image/png",
            "multiple": true,
            "pattern": "outfile*.png"
          }
        ]
      }
    }
  }
}
```

UI request header upon creation:
```
{
  "icon_code":"f2b9",
  "docker_image":"docker.io/emimaesmith/mini-job-1.0.0-seed:1.0.0",
  "manifest":{
    "seedVersion":"1.0.0",
    "job":{
      "name":"mini-job",
      "jobVersion":"1.0.0",
      "packageVersion":"1.0.0",
      "title":"Mini Job",
      "description":"Super Mini Job",
      "tags":["mini"],
      "maintainer":{
        "name":"Emily Smith","email":"jdoe@example.com",
      },
      "timeout":3600,
      "interface":{
        "command":"${OUTPUT_DIR}",
        "inputs":{"files":null},
        "outputs":{
          "files":[
          
{"name":"output_file_pngs","mediaType":"image/png","multiple":true,"pattern":"outfile*.png","required":true}
          ],
        },
      },
      "resources":{"scalar":null}
    },
  },
  "configuration":{"output_workspaces":{"default":"testing-output"},"priority":100},
}
```
Note the null `inputs:files` and `resources:scalar`.

**Comment by JohnPTobe** [comment] 2019-07-16 13:54
> 
> 
> @JohnPTobe maybe we discussed this, but I can't remember. How should I decide whether to use the PATCH vs POST endpoints? Should I go by whether a field can be changed via PATCH?

If we discussed it, it was a long time ago.  I'd say use POST if we're updating docker_image and/or the manifest.

**Comment by JohnPTobe** [comment] 2019-07-16 13:59
Maybe allow for getting image info again from silo on the edit page.  If the user does that, make a post request and only allow post fields.  Otherwise treat it as a patch.  Or do both calls when those fields are updated so all fields from post/patch endpoints can be set.

**Comment by emimaesmith** [comment] 2019-07-18 13:16
Is the job type name and version being lost during an edit? Editing a job type will try and call `/job-types/undefined/undefined` when saving. This, obviously, throws a 404 not found.

**Comment by ericsvendsen-mil** [comment] 2019-07-22 15:06
Here's what's left:
* Add inputs for editing boolean fields
* Add input for editing `docker_image` field. When this has been changed, a POST needs to happen
* Look into Emily's above question
* Then close this issue

**Closed** 2019-07-26 04:52 UTC
Labels: Required for Scale 7.0
