### ISSUE TITLE
Issue on Date Time Picker in Processing-Recipes View

### ISSUE THREAD

**Issue by SaraDarrah** [ngageoint/scale-ui#299] opened 2019-08-31 01:39 UTC
Click on Processing-Recipes
Recipe Date Picker- chose 8-1 to current date
Last Modified by comes up as "a month ago"  but I only chose a time range within this month.

**Comment by mheppner** [comment] 2020-02-26 21:55
Duplicate of #297 and #303.

**Closed by mheppner** 2020-02-26 21:55 UTC
