### ISSUE TITLE
Unknown recipe editor bug?

### ISSUE THREAD

**Issue by mheppner** [ngageoint/scale-ui#475] opened 2020-04-17 13:23 UTC
From Sara:

> inputs aren't always staying, and sometimes you add/remove jobs but then dependencies won't show up.

Reproduction steps are not available.

**Comment by Fizz11** [comment] 2020-04-17 17:07
Specifically after setting an input on a job node and closing the node, when you re-open the job node inputs are still unassigned. 

It seems rather intermittent. I've encountered it twice but cant recall the exact steps to reproduce. both times i had added, set dependencies and file inputs, and removed multiple job recipe and conditional nodes. 

On one hand it is probably an extreme edge case, but on the other it could be frustrating to encounter after spending 45+min creating a complex recipe only to find it will not validate due to an obscure UI bug.

**Comment by mheppner** [comment] 2020-05-26 20:57
Possible steps (using mock data built into UI):
1. Add job "constrained energy minimization" (a job that has two+ slots for inputs)
2. Add a file input (anything)
3. Back in the recipe, click the job node to open the modal
4. Add your file input to both slots of the input (same file input to each) -> both appear as desired
5. Close the modal
6. Click the job node again to open the modal -> only the first input slot has the file input, the other one is empty

This is at least one issue found. The recipe definition is built correctly (I can see that the recipe.definition.nodes.cem.input has both entries filled out with the file input), it just looks like a rendering issue in the modal.

**Comment by Nikkala-AIS** [comment] 2020-06-18 13:20
I can confirm duplication of this issue as mheppner replicated it.  However, if you set up two different inputs and assign one to each different input, this issue does not occur.

**Comment by Fizz11** [comment] 2020-06-18 17:32
Closing this issue as we haven't been able to reproduce the original problem. created two new issues that were found while trying to reproduce issue ( #490 #491 )

**Closed by Fizz11** 2020-06-18 17:32 UTC
